version: "3.3"
services:
  boatpilot:
    image: boatpilot
    privileged: true
    depends_on:
        #      - prom
      - gpsd
    ports:
      - "80:8000"
    volumes:
      - boatpilotetc:/etc/boatpilot
      - ./app:/usr/src/app # for developing.
    devices:
      - "/dev/mem"
      - "/dev/gpiomem"
      - "/dev/input:/dev/input"
    cap_add:
        - SYS_RAWIO

  gpsd:
    image: forcedinductionz/docker-gpsd:latest-armhf
    devices: 
      - "/dev/serial/by-id/usb-u-blox_AG_-_www.u-blox.com_u-blox_6_-_GPS_Receiver-if00:/dev/ttySS0"
    command: "/dev/ttySS0"
    ports:
      - "127.0.0.1:2947:2947"

        #  grafana:
        #    image: grafana/grafana
        #    depends_on:
        #      - prom
        #    volumes:
        #      - grafanadata:/var/lib/grafana
        #    ports:
        #      - "3000:3000"
        #
        #  prom:
        #    image: prom/prometheus

volumes:
    #  prometheusdata:
    #  grafanadata:
  boatpilotetc:
